config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "pages#hello"
  get "about", to: "pages#about"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article,  only: [ :show, :edit, :update, :destroy ]

  def show
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to articles_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.delete
    redirect_to article_path(@article)
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def hello
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <% @article.errors.full_messages.each do |error_message| %>
    <p color='red'><%= error_message %></p>
  <% end %>  
<% end%>
<%= form_with(model: @article, local: true) do |f| %>
  <p>
    <%= f.label :title%></br>
    <%= f.text_field :title %>
  </p>
  <p>  
    <%= f.label :description %></br>
    <%= f.text_area :description %>
  </p>  
  <p>
    <%= f.submit "Save Article" %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<p>Edit article</p>

<%= render 'form'%>
<p>
  <%= link_to "Cancel and return to articles page", articles_path %>
</p>

app/views/articles/index.html.erb
<h1>Articles Listing Page</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to "Show", article_path(article) %></td>
        <td><%= link_to "Edit", edit_article_path(article) %></td>
        <td><%= link_to "Delete", article_path(article), data: { turbo_method: "delete" } %></td>
      </tr>
    <% end %>
    <p><%= link_to "Create", new_article_path %></p>
  </tbody>
</table>

app/views/articles/new.html.erb
<p>Creating a new article</p>

<%= render 'form' %>
<p>
  <%= link_to "Cancel and return to articles page", articles_path %>
</p>

app/views/articles/show.html.erb
<h1>Showing articles</h1>
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
<p>
  <strong>Body:</strong>
  <%= @article.description %>
</p>
<p>
    <%= link_to "Cancel and return to articles page", articles_path %>
</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %> 
  <%= msg %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Alpha Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the About page</h1>

<p>
    <%= link_to "Articles listing", articles_path %>
    <%= link_to "Home page", root_path %>
  </p>

app/views/pages/hello.html.erb
<p>Hello world</p>

<p>
    <%= link_to "Articles listing", articles_path %>
    <%= link_to "About page", about_path %>
  </p>

app/views/pages/home.html.erb
<p>Hello world</p>